#!/usr/bin/env bash

function state {
    THEME=$(gsettings get org.gnome.desktop.interface color-scheme)
    if [[ $THEME == "'prefer-dark'" ]]; then echo 'on'
    else echo 'off'; fi
}

function toggle {
    STATE=$(state)
    if [[ $STATE == 'on' ]]; then
        gsettings set org.gnome.desktop.interface color-scheme "'default'"
        cp $HOME/.config/eww/scss/colors_light.scss $HOME/.config/eww/scss/colors.scss
    else
        gsettings set org.gnome.desktop.interface color-scheme "'prefer-dark'"
        cp $HOME/.config/eww/scss/colors_dark.scss $HOME/.config/eww/scss/colors.scss
    fi

    swaync-client --reload-css
    eww update theme_state=$(state)
    bash $HOME/.config/eww/scripts/init
}

if [[ $1 == 'toggle' ]]; then toggle; fi
if [[ $1 == 'state' ]]; then state; fi