keys:
  - &isabel age16sj4v4y0ny784kwsrs0x9vayrwy8avj0na3tmd87jsa692dte3nsj8z8m6
  - &server age19ew6667achxf6pdxapackdq3zq2y0kd4lxvf7u7hu6cyku0fay0szq5fsk
creation_rules:
  - path_regex: home/isabel/system/secrets.yaml
  - key_groups:
    - age:
      - *isabel
  - path_regex: modules/common/types/server/system/secrets.yaml
  - key_groups:
    - age:
      - *server
