{
  imports = [
    ./command-not-found.nix
    ./earlyoom.nix
    ./firmware.nix
    ./flatpak.nix
    ./gnome.nix
    ./location.nix
    ./logind.nix
    ./loginManager.nix
    ./logs.nix
    ./misc.nix
    ./monitoring.nix
    ./oomd.nix
    ./pager.nix
    ./printing.nix
    ./runners.nix
    ./seatd.nix
    ./serial.nix
    ./size.nix
    ./systemd.nix
    ./xdg-portals.nix
    ./xserver.nix
  ];
}
