#!/usr/bin/env bash

function screen_icon {
	ARRAY=('󰛩' '󱩎' '󱩏' '󱩐' '󱩑' '󱩒' '󱩓' '󱩔' '󱩕' '󱩖' '󰛨')
	IND=$(($(screen_level) / 10))
	echo ${ARRAY[$IND]}
}

function screen_level {
	echo $(brightnessctl info | awk -F "(" '{print $2}' | tr -d "%)")
}

function raise_screen {
	brightnessctl set 5%+ -q
	update_screen
}

function lower_screen {
	brightnessctl set 5%- -q
	update_screen
}

function update_screen {
	eww update brightness="$(get)"
	~/.config/eww/scripts/./osd $(screen_icon) $(screen_level)
}

function set_screen {
	brightnessctl set $1"%" -q
	eww update brightness="$(get)"
}

function get {
	echo "{
		\"screen\": { \"level\": \"$(screen_level)\", \"icon\": \"$(screen_icon)\" }
	}"
}

if [[ $1 == 'get' ]]; then get; fi
if [[ $1 == 'up' ]]; then raise_screen; fi
if [[ $1 == 'down' ]]; then lower_screen; fi
if [[ $1 == 'set_screen' ]]; then set_screen $2; fi
