#!/usr/bin/env bash

EWW_DIR=$HOME/.config/eww/bel

killall eww
eww daemon

HDMI=$(hyprctl monitors -j | jq .[1].name)

if [[ $HDMI == '"HDMI-A-1"' ]]; then
    eww -c $EWW_DIR open secondarybar
    eww -c $EWW_DIR open bar1
    eww -c $EWW_DIR update main_monitor=1
else
    eww -c $EWW_DIR open bar0
    eww -c $EWW_DIR update main_monitor=0
fi