#!/usr/bin/env bash

EWW_DIR=$HOME/.config/eww/bel

function toggle_menu {
    MAIN=$(eww -c $EWW_DIR get main_monitor)
    STATE=$(eww windows -c $EWW_DIR | grep $1$MAIN | awk '{print substr ($0, 0, 1)}')
    if [[ $STATE == '*' ]]; then 
        eww -c $EWW_DIR close $1$MAIN;
    else
        eww -c $EWW_DIR open $1$MAIN;
    fi
}

function close_osd {
    notify-send asd
}

function network {
    alacritty -e fish -c iwctl
}

function applauncher {
    STATE0=$(eww windows -c $EWW_DIR | grep powermenu | awk '{print substr ($0, 0, 1)}')
    STATE1=$(eww windows -c $EWW_DIR | grep quicksettings | awk '{print substr ($0, 0, 1)}')
    STATE2=$(eww windows -c $EWW_DIR | grep calendar | awk '{print substr ($0, 0, 1)}')
    STATE3=$(eww windows -c $EWW_DIR | grep osd | awk '{print substr ($0, 0, 1)}')
    if [[ $STATE0 == '*' ]]; then eww -c $EWW_DIR close powermenu0 && eww -c $EWW_DIR close powermenu1; fi
    if [[ $STATE1 == '*' ]]; then eww -c $EWW_DIR close quicksettings0 && eww -c $EWW_DIR close quicksettings1; fi
    if [[ $STATE2 == '*' ]]; then eww -c $EWW_DIR close calendar0 && eww -c $EWW_DIR close calendar1; fi
    if [[ $STATE3 == '*' ]]; then eww -c $EWW_DIR close osd0 && eww -c $EWW_DIR close osd1; fi
    killall rofi || rofi -show drun -theme ~/.config/rofi/themes/catppuccin-mocha.rasi
}

function config {
    alacritty -e micro $HOME/.config/hypr/hyprland.conf
}

function documents {
    thunar $HOME/Documents
}

function downloads {
    thunar $HOME/Downloads
}

function pictures {
    thunar $HOME/Pictures
}

function videos {
    thunar $HOME/Videos
}

function notifications {
    STATE0=$(eww windows -c $EWW_DIR | grep powermenu | awk '{print substr ($0, 0, 1)}')
    STATE1=$(eww windows -c $EWW_DIR | grep quicksettings | awk '{print substr ($0, 0, 1)}')
    STATE2=$(eww windows -c $EWW_DIR | grep calendar | awk '{print substr ($0, 0, 1)}')
    STATE3=$(eww windows -c $EWW_DIR | grep osd | awk '{print substr ($0, 0, 1)}')
    if [[ $STATE0 == '*' ]]; then eww -c $EWW_DIR close powermenu0 && eww -c $EWW_DIR close powermenu1; fi
    if [[ $STATE1 == '*' ]]; then eww -c $EWW_DIR close quicksettings0 && eww -c $EWW_DIR close quicksettings1; fi
    if [[ $STATE2 == '*' ]]; then eww -c $EWW_DIR close calendar0 && eww -c $EWW_DIR close calendar1; fi
    if [[ $STATE3 == '*' ]]; then eww -c $EWW_DIR close osd0 && eww -c $EWW_DIR close osd1; fi
    swaync-client -t
}

function wlogout {
	STATE0=$(eww windows -c $EWW_DIR | grep powermenu | awk '{print substr ($0, 0, 1)}')
    STATE1=$(eww windows -c $EWW_DIR | grep quicksettings | awk '{print substr ($0, 0, 1)}')
    STATE2=$(eww windows -c $EWW_DIR | grep calendar | awk '{print substr ($0, 0, 1)}')
    STATE3=$(eww windows -c $EWW_DIR | grep osd | awk '{print substr ($0, 0, 1)}')
    if [[ $STATE0 == '*' ]]; then eww -c $EWW_DIR close powermenu0 && eww -c $EWW_DIR close powermenu1; fi
    if [[ $STATE1 == '*' ]]; then eww -c $EWW_DIR close quicksettings0 && eww -c $EWW_DIR close quicksettings1; fi
    if [[ $STATE2 == '*' ]]; then eww -c $EWW_DIR close calendar0 && eww -c $EWW_DIR close calendar1; fi
    if [[ $STATE3 == '*' ]]; then eww -c $EWW_DIR close osd0 && eww -c $EWW_DIR close osd1; fi
	wlogout -b 5 -T 400 -B 400 &
}

if [[ $1 == 'applauncher'    ]]; then applauncher; fi
if [[ $1 == 'documents'      ]]; then documents; fi
if [[ $1 == 'downloads'      ]]; then downloads; fi
if [[ $1 == 'pictures'       ]]; then pictures; fi
if [[ $1 == 'videos'         ]]; then videos; fi
if [[ $1 == 'pavu'           ]]; then pavucontrol; fi
if [[ $1 == 'network'        ]]; then network; fi
if [[ $1 == 'brightness'     ]]; then wl-gammactl; fi
if [[ $1 == 'bluetooth'      ]]; then blueberry; fi
if [[ $1 == 'powermenu'      ]]; then powermenu; fi
if [[ $1 == 'toggle_menu'    ]]; then toggle_menu $2; fi
if [[ $1 == 'close_menu'     ]]; then close_menu $2; fi
if [[ $1 == 'close_osd'      ]]; then close_osd; fi
if [[ $1 == 'close_calendar' ]]; then close_calendar; fi
if [[ $1 == 'config'         ]]; then config; fi
if [[ $1 == 'notifications'  ]]; then notifications; fi
if [[ $1 == 'wlogout'        ]]; then wlogout; fi
