name: Validate Nix Flake

on:
  workflow_call:
    inputs:
      system:
        required: true
        type: string
        description: "The system to install Lix for"
      os:
        required: true
        type: string
        description: "The operating system to install Lix for"

jobs:
  check-flake:
    name: Check (${{ matrix.system }})
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Lix
        uses: .github/actions/install-lix.yml
        with:
          system: ${{ matrix.system }}
          os: ${{ matrix.os }}

      - name: Check Flake
        run: nix flake check
