#!/usr/bin/env bash

socat -u UNIX-CONNECT:/tmp/hypr/"$HYPRLAND_INSTANCE_SIGNATURE"/.socket2.sock - | while read -r line; do
	formattedWorkspaces=()

	workspaces=$(hyprctl workspaces -j)
	activeWorkspace=$(hyprctl activeworkspace -j)
	active_id=$(echo "$activeWorkspace" | jq -r '.id')

	while IFS= read -r w; do
		id=$(echo "$w" | jq -r '.id')
		focus=$(if [[ $id -eq $active_id ]]; then echo "focus"; else echo ""; fi)

		# Add the formatted workspace object to the array
		formattedWorkspaces+=("{\"id\": $((id - 1)), \"focus\": \"$focus\"}")
	done <<<"$(echo "$workspaces" | jq -c '.[]')"

	sortedWorkspaces=$(printf '%s\n' "${formattedWorkspaces[@]}" | jq -s 'sort_by(.id)')

	# Print the formatted workspaces array in JSON format
	printf '%s\n' "$sortedWorkspaces" | jq -c .
done
