name: Install Lix
description: "Install Lix for the specified system"

inputs:
  system:
    required: true
    description: "The system to install Lix for"

runs:
  using: composite

  steps:
    - uses: DeterminateSystems/nix-installer-action@main
      with:
        source-url: https://install.lix.systems/lix/lix-installer-${{ inputs.system }}
        logger: pretty
        diagnostic-endpoint: ""
        extra-conf: |
          experimental-features = flakes nix-command recursive-nix pipe-operator
          substituters = https://nix-community.cachix.org https://isabelroses.cachix.org https://catppuccin.cachix.org https://cache.nixos.org/
          trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= nix-community.cachix.org-1:mB9FSh9qf2dCimDSUo8Zy7bkq5CX+/rkCWyvRCYg3Fs= isabelroses.cachix.org-1:mXdV/CMcPDaiTmkQ7/4+MzChpOe6Cb97njKmBQQmLPM= catppuccin.cachix.org-1:noG/4HkbhJb+lUAdKrph6LaozJvAeEEZj4N732IysmU=
