#!/usr/bin/env bash

function screenlock {
	STATE0=$(eww windows | grep powermenu | awk '{print substr ($0, 0, 1)}')
    STATE1=$(eww windows | grep quicksettings | awk '{print substr ($0, 0, 1)}')
    STATE2=$(eww windows | grep calendar | awk '{print substr ($0, 0, 1)}')
    STATE3=$(eww windows | grep osd | awk '{print substr ($0, 0, 1)}')
    if [[ $STATE0 == '*' ]]; then eww close powermenu0 && eww close powermenu1; fi
    if [[ $STATE1 == '*' ]]; then eww close quicksettings0 && eww close quicksettings1; fi
    if [[ $STATE2 == '*' ]]; then eww close calendar0 && eww close calendar1; fi
    if [[ $STATE3 == '*' ]]; then eww close osd0 && eww close osd1; fi
	swaylock
}

function reboot {
    systemctl reboot
}

function suspend {
    systemctl suspend
}

function poweroff {
    systemctl poweroff
}

function logout {
    hyprctl dispatch exit 0
}

if [[ $1 == 'reboot'        ]]; then reboot; fi
if [[ $1 == 'logout'        ]]; then logout; fi
if [[ $1 == 'poweroff'      ]]; then poweroff; fi
if [[ $1 == 'suspend'       ]]; then suspend; fi
if [[ $1 == 'screenlock'    ]]; then screenlock; fi
