#!/usr/bin/env bash

function query {
	dbus-send --session --type=method_call \
		--dest=com.github.isabel.host \
		/com/github/isabel/applications \
		com.github.isabel.applications.Query \
		string:$1
}

if [[ $1 == 'query' ]]; then query $2; fi

