#!/usr/bin/env bash

pkill eww
pkill $(ps aux | grep host | awk 'FNR == 1 {print $2}')
eww daemon

# HDMI=$(hyprctl monitors -j | jq .[1].name)
# if [[ $HDMI == '"HDMI-A-1"' ]]; then
#     # open both monitor stuff
# else
#     # open main monitror stuff
# fi

eww open bar
# eww open dock
eww open desktop
sleep 1s
eww open notifications_popup
# eww inspector

$HOME/.config/eww/scripts/host/./host --eww --file
