#!/usr/bin/env bash

pkill eww
kill $(ps aux | rg host | awk 'FNR == 1 {print $2}')
eww daemon

eww open bar
eww open desktop
eww open notifications_popup
# eww inspector

$HOME/.config/eww/scripts/host/./host --eww --file
