#!/usr/bin/env bash

function toggle_menu {
  hyprctl keyword blurls "remove,gtk-layer-shell"
  STATE=$(eww windows | grep $1 | awk '{print substr ($0, 0, 1)}')
  if [[ $STATE == '*' ]]; then
    # if [[ $1 == 'powermenu' ]]; then hyprctl keyword blurls "remove,gtk-layer-shell"; fi
    eww close $1
  else
    if [[ $1 == 'powermenu' ]]; then hyprctl keyword blurls "gtk-layer-shell"; fi
    if [[ $1 == 'app_launcher' ]]; then $HOME/.config/eww/scripts/apps query ""; fi
    eww open $1
  fi
}

function colorpicker {
  pkill hyprpicker
  hyprpicker -n -a
}

function network {
  nm-connection-editor
}

function screenlock {
  STATE=$(eww windows | grep powermenu | awk '{print substr ($0, 0, 1)}')
  if [[ $STATE == '*' ]]; then eww close powermenu; fi
  swaylock
}

function clipboard {
  cliphist list | rofi -dmenu -p "Clipboard" | cliphist decode | wl-copy
}

function config {
  $VISUAL $HOME/.config/hypr
}

function powersettings {
  alacritty --class Power --title Power --hold \
    --command auto-cpufreq --stats
}

if [[ $1 == 'applauncher' ]]; then rofi -show drun; fi
if [[ $1 == 'clipboard' ]]; then clipboard; fi
if [[ $1 == 'pavu' ]]; then pavucontrol; fi
if [[ $1 == 'network' ]]; then network; fi
if [[ $1 == 'brightness' ]]; then wl-gammactl; fi
if [[ $1 == 'bluetooth' ]]; then blueberry; fi
if [[ $1 == 'powermenu' ]]; then powermenu; fi
if [[ $1 == 'toggle_menu' ]]; then toggle_menu $2; fi
if [[ $1 == 'close_calendar' ]]; then close_calendar; fi
if [[ $1 == 'colorpicker' ]]; then colorpicker; fi
if [[ $1 == 'picker' ]]; then picker; fi
if [[ $1 == 'screenlock' ]]; then screenlock; fi
if [[ $1 == 'config' ]]; then config; fi

if [[ $1 == 'editor' ]]; then alacritty --command $EDITOR; fi
