#!/usr/bin/env bash
VOLUME=$(pamixer --get-volume)
MUTED=$(pamixer --get-mute)

function icon {
  if [[ $MUTED == false ]]; then
    if [[ $VOLUME -ge 66 ]]; then
      echo '󰕾'
    elif [[ $VOLUME -ge 33 ]]; then
      echo '󰖀'
    elif [[ $VOLUME -ge 1 ]]; then
      echo '󰕿'
    else
      echo '󰝟'
    fi
  else
    echo '󰝟'
  fi
}

function level {
  if [[ $MUTED == true ]]; then
    echo 0
  else
    echo $VOLUME
  fi
}

function lower {
  pamixer -d 5
  update
}

function raise {
  pamixer -i 5
  update
}

function mute {
  pamixer --toggle-mute
}

function update {
  eww update volume="$(get)"
  ~/.config/eww/scripts/osd $(icon) $(level)
}

function type_icon {
  echo "󰋋"
  #else
  #  echo "󰓃"
  #fi
}

function mic_mute_state {
  STATE=$(pamixer --default-source --get-mute)
  if [[ $STATE == false ]]; then
    echo 'off'
  else echo 'on'; fi
}

function mic_mute_icon {
  STATE=$(mic_mute_state)
  if [[ $STATE == 'off' ]]; then
    echo '󰍬'
  else echo '󰍭'; fi
}

function mute_mic {
  pamixer --default-source -t
  eww update volume="$(get)"
}

function set {
  pamixer --set-volume $1
  eww update volume="$(get)"
}

function get {
  echo "{
  \"level\": \"$(level)\",
  \"icon\": \"$(icon)\",
  \"type_icon\": \"$(type_icon)\",
  \"mute\": {
  \"state\": \"$(mic_mute_state)\",
  \"icon\": \"$(mic_mute_icon)\"
}
}"
}

if [[ $1 == 'mute_mic' ]]; then mute_mic; fi
if [[ $1 == 'down' ]]; then lower; fi
if [[ $1 == 'up' ]]; then raise; fi
if [[ $1 == 'mute' ]]; then mute; fi
if [[ $1 == 'set' ]]; then set $2; fi
if [[ $1 == 'get' ]]; then get; fi
