#!/usr/bin/env bash

ewwdir=$HOME/.config/eww/bel

function toggle {
    STATE=$(state)
    STATE0=$(eww -c $ewwdir windows | grep powermenu | awk '{print substr ($0, 0, 1)}')
    STATE1=$(eww -c $ewwdir windows | grep quicksettings | awk '{print substr ($0, 0, 1)}')
    STATE2=$(eww -c $ewwdir windows | grep calendar | awk '{print substr ($0, 0, 1)}')
    STATE3=$(eww -c $ewwdir windows | grep osd | awk '{print substr ($0, 0, 1)}')
    if [[ $STATE0 == '*' ]]; then eww -c $ewwdir close powermenu0 && eww -c $ewwdir close powermenu1; fi
    if [[ $STATE1 == '*' ]]; then eww -c $ewwdir close quicksettings0 && eww -c $ewwdir close quicksettings1; fi
    if [[ $STATE2 == '*' ]]; then eww -c $ewwdir close calendar0 && eww -c $ewwdir close calendar1; fi
    if [[ $STATE3 == '*' ]]; then eww -c $ewwdir close osd0 && eww -c $ewwdir close osd1; fi
    if [[ $STATE == 'on' ]]; then
        eww-c $ewwdir update dnd_icon=󰂚
        eww-c $ewwdir update dnd_status=off
        swaync-client --dnd-off
    else
        eww-c $ewwdir update dnd_icon=󰂛
        eww-c $ewwdir update dnd_status=on
        swaync-client --dnd-on
    fi
}

function icon {
    STATE=$(swaync-client --get-dnd)
    if [[ $STATE == 'false' ]]; then echo '󰂚';
    else echo '󰂛'; fi 
}

function state {
    STATE=$(swaync-client --get-dnd)
    if [[ $STATE == 'false' ]]; then echo 'off'
    else echo 'on'; fi
}

if [[ $1 == 'toggle' ]]; then toggle; fi
if [[ $1 == 'icon' ]]; then icon; fi
if [[ $1 == 'state' ]]; then state; fi
if [[ $1 == 'count' ]]; then swaync-client --count; fi
if [[ $1 == 'open' ]]; then swaync-client --open-panel; fi
