default:
  just --list

flags := "-xelatex -synctex=1 -interaction=nonstopmode --file-line-error --shell-escape -outdir=out -aux-directory=aux --8bit"
file := "index.tex"

build:
  latexmk {{flags}} {{file}}

watch:
  latexmk {{flags}} -pvc -view=none {{file}}

clean:
  rm -rv out
