name: Validate Nix Flake

on:
  workflow_dispatch:
  push:
    paths:
      - "**.nix"
      - "**.lock"
      - ".github/workflows/check.yml"
      - ".github/actions/**/*"

permissions: {}

jobs:
  check-flake:
    name: Check (${{ matrix.system }})
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            system: x86_64-linux
          - os: macos-latest
            system: aarch64-darwin

    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false

      - name: Install Lix
        uses: ./.github/actions/install-lix

      - name: Check Flake
        run: nix develop -c just check --show-trace
