name: Validate Flake Formatting

on: [push, workflow_dispatch]

jobs:
  check-formatting:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v23
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - run: nix run nixpkgs#alejandra -- -c .
